### ISSUE TITLE
Discord Link 

### ISSUE THREAD

**Issue by theabhayprajapati** [silvia-odwyer/pixels.js#10]
Can you please make a Discord link for this so that we can communicate easier, or should I make one.

**Comment by silvia-odwyer** [comment]
@theabhayprajapati Unfortunately there aren't plans for a Discord server for this library at this time. Sorry about this! Of course, if you'd like to open issues, discuss new features etc, feel free to open issues here and I'll help out however I can.

**Comment by theabhayprajapati** [comment]
sure no problem.
