### ISSUE TITLE
`npm run build:browser` is giving errors.

### ISSUE THREAD

**Issue by theabhayprajapati** [silvia-odwyer/pixels.js#7]
<img width="588" alt="image" src="https://user-images.githubusercontent.com/88815641/194698708-eaec6167-0958-4bdb-a291-68eb7bf923c1.png">

getting some sort of babel error while building the module.

**Comment by silvia-odwyer** [comment]
@theabhayprajapati It's working for me, what version of Webpack are you using may I ask?

**Comment by theabhayprajapati** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/88815641/198836627-3c7b46be-1113-4229-96d5-49213f567328.png">

@silvia-odwyer Hey i am using 
```bash
    "webpack": "^4.4.1",

```

**Comment by theabhayprajapati** [comment]
it's fixed now thanks' @silvia-odwyer
